on:
  - pull_request

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: multiline message
        shell: bash
        run: |
          set -e
          msg="foo\nbar\nbaz"
          echo "::group::example group"
          echo -e "$msg"
          echo "this is stderr" >&2
          echo "this is stdout"
          echo "::endgroup::"
        

