on:
  - pull_request

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: multiline message
        shell: bash
        run: |
          set -e
          msg="$(echo -e "foo\nbar\nbaz")"
          echo "::notice::$msg"
        

